[FIX]  Passphrase Warning
erpbrasil/erpbrasil.assinatura pull request #28
Opened 2022-01-18 00:13 UTC by netosjb

Trivial FIX para corrigir o warning a baixo que está impedindo o trevis do odoo 14.0 ficar verdinho:

> 2022-01-16 14:42:17,463 166 WARNING openerp_test py.warnings: /.repo_requirements/virtualenv/python3.6/lib/python3.6/site-packages/erpbrasil/assinatura/certificado.py:30: DeprecationWarning: str for passphrase is no longer accepted, use bytes
> self._senha)

2022-01-18 00:55 UTC, felipemotter approved these changes

2022-01-18 06:36 UTC, rvalyi commented
que tal fazer um teste como `if type(senha) == str:` e chamar o encode() so nesse caso. Porque se a lib crypto quer uma senha em bytes em vez de str, a logica seria que alguem possa passar uma senha em bytes tb para a lib erpbrasil.assinatura. Vc não acharia mais consistente?

2022-01-18 12:08 UTC, netosjb commented
boa @rvalyi , mas agora você me fez pensar melhor e acho que  o correto é a lib nem aceitar a entrada do parâmetro da senha como texto, melhor a lib cobrar que seja obrigatório um binary e nem fazemos essa transformação ali.

A gente pode fazer a correção diretamente no odoo, lá na classe certificado podemos alterar para que o field password seja um binary e não um char, aqui: https://github.com/OCA/l10n-brazil/blob/3fa25654bc465aecc53c162f90777ebfdbb53f47/l10n_br_fiscal/models/certificate.py#L73 e ai a gente já faz esse tratamento correto desde o inicio da operação dentro do odoo.

o que acha ?

2022-01-19 13:19 UTC, renatonlima requested changes
@netosjb,

Eu acho interessante fazer a sugestão do @rvalyi de verificar se a argumento senha é uma string e converte-la para byte para resolver o problema de warning e deixar o código consistente.

2022-01-19 13:35 UTC, netosjb commented
@rvalyi @renatonlima 

Beleza! vou incluir a validação conforme proposto por Raphael valeu

2022-01-19 23:56 UTC, netosjb commented
@rvalyi @renatonlima 

Adicionei e verificação, separei a logica em  um método e adicionei um teste, é um teste bobo mas só para garantir que está tudo certo mesmo.

ping @mileo

2022-01-20 00:21 UTC, renatonlima approved these changes

2022-01-20 13:33 UTC, marcelsavegnago approved these changes

2022-01-20 14:59 UTC, netosjb commented
fiz um push para arrumar o nome do método de _encodeSenha para _encode_senha, para ficar de acordo com convenção Python. ( eu era programador java rss. )

2022-01-29 18:19 UTC, netosjb commented
@mileo 

podemos dar merge nesta pr ?

2022-02-05 00:03 UTC, rvalyi approved these changes

2022-02-05 00:07 UTC, rvalyi commented
Apenas a KMEE tem direitos nesse repo. Se o repo continuar sem manutençao da KMEE na minha opiniao temos que criar um repo e pacote alternativo, pelo menos ate eles conseguir dar conta de manter o que pretendem manter, pois nao da para travar tudo na OCA por conta de questões tão triviais de se revisar...

2022-03-09 08:59 UTC, netosjb commented
Ping @mileo

2022-03-09 14:38 UTC, rvalyi commented
@netosjb eu já vou fazer 2 PRs para completar o que vc fez e o que o Renato fez porque faltava uns ajustes.

2022-03-11 12:01 UTC, renatonlima approved these changes

2022-03-11 12:01 UTC, merged